Feat/support identity link
citilinkru/camunda-client-go pull request #44
Opened 2022-10-08 13:59 UTC by qs-wang

2023-01-09 15:38 UTC, liderman requested changes

2023-01-09 15:38 UTC, liderman commented on user-task.go
> +		return nil, fmt.Errorf("can't complete task: %w", err)
looks like copy paste.
I think it's worth doing this:
```go
return nil, fmt.Errorf("can't get identity links: %w", err)
```

2023-01-09 15:38 UTC, liderman commented on user-task.go
> +		return fmt.Errorf("can't complete task: %w", err)
I think it's worth doing this:
```go
return nil, fmt.Errorf("can't add identity link: %w", err)
```

2023-01-09 15:38 UTC, liderman commented on user-task.go
> +		return fmt.Errorf("can't complete task: %w", err)
I think it's worth doing this:
```go
return fmt.Errorf("can't delete identity link: %w", err)
```

2023-01-10 11:41 UTC, qs-wang commented
@liderman thanks for the review. Messages are fixed.

2023-01-13 10:45 UTC, merged

2023-01-13 10:50 UTC, liderman commented
@qs-wang thanks for the fixes.
Changes included in release [v3.3.0](https://github.com/citilinkru/camunda-client-go/releases/tag/v3.3.0)